@echo off
echo Updating ngrok...
"C:\Users\mikat\AppData\Local\Microsoft\WinGet\Packages\Ngrok.Ngrok_Microsoft.Winget.Source_8wekyb3d8bbwe\ngrok.exe" update
echo Adding auth token...
"C:\Users\mikat\AppData\Local\Microsoft\WinGet\Packages\Ngrok.Ngrok_Microsoft.Winget.Source_8wekyb3d8bbwe\ngrok.exe" config add-authtoken 3F97Pk4fxHKQmqMp2X6u0rjcom6_xocctKEpkA6vTboxxAcg
echo Starting tunnel...
"C:\Users\mikat\AppData\Local\Microsoft\WinGet\Packages\Ngrok.Ngrok_Microsoft.Winget.Source_8wekyb3d8bbwe\ngrok.exe" http 8000
pause
